### PR TITLE
Implemented "reserve" command for IPAM interface.

### PR DESCRIPTION
**Pull request by karya0**
This allows us to reserve static IPs, passed by the framework, with the IPAM server.

### CODE REVIEW

**Comment by spikecurtis** [comment]
Unfortunately this isn't sufficient for static container IPs.  We need to extend the IPAM API to allow Agents to request specific IP addresses, otherwise the IPAM system won't know the address is taken an could assign it to a different container.

**Comment by karya0** [comment]
Updated the PR to add the "reserve" command for IPAM.

**Comment by spikecurtis** [comment]
@djosborne can you try your code out with this?  Or should I just merge (e.g. OK to temporarily break the integration branch until your stuff is in)?

**Comment by djosborne** [comment]
I updated the calico binary, fixed the demos, and fixed a typo in the isolator in #44. We can close this one

**Pull request closed without merging**
