### PR TITLE
Add RPM builder

### PR DESCRIPTION
**Pull request by titilambert**

### CODE REVIEW

**Comment by djosborne** [comment]
@titilambert First of all, thanks for the contribution here, we've been testing this out and its working great. After having gotten my hands dirty, I wanted to ask about your decision to create the `mesos-init-wrapper` script. AFAICT, the functionality you've developed can already be attained by setting proper environment files and referencing them in the systemd service files. Is there a particular reason you've pushed this functionality into your wrapper script?

**Comment by titilambert** [comment]
Hello,
I just get example from mesosphere packages.
It's just to get transition safe and easy.

**Comment by spikecurtis** [comment]
@titilambert Sorry for the delay!  Mesosphere require contributors to sign a contribution agreement before we can merge.

Download: https://dl.dropboxusercontent.com/u/4550074/CLAMesosphere.docx

Email to: tarak@mesosphere.io

Let me know when you've done so.

**Comment by djosborne** [comment]
@titilambert Have you had a chance to sign the contribution agreement? We're eager to merge your work!

**Comment by titilambert** [comment]
@djosborne yeah! what I have to do ?

**Comment by titilambert** [comment]
Oki ! I will do this in a few day

**Comment by titilambert** [comment]
@spikecurtis @djosborne Just sent ;)

**Pull request merged**
